# Generated by Django 4.0.1 on 2024-07-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
