# Generated by Django 4.0.1 on 2024-07-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
